version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: sk-realtimeapp-postgres
    restart: always
    environment:
      POSTGRES_USER: sk_realtimeapp_user
      POSTGRES_PASSWORD: sk_realtimeapp_password
      POSTGRES_DB: sk_realtimeapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sk-realtimechat-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sk-realtimeapp-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sk-realtimeapp.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - sk-realtimechat-network
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: sk-realtimeapp-redis
    restart: always
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--requirepass", "sk_realtimeapp_redis_password"
      ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sk-realtimechat-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: sk-realtimeapp-redis-commander
    restart: always
    environment:
      REDIS_HOSTS: local:redis:6379:0:sk_realtimeapp_redis_password
      HTTP_USER: sk_realtimeapp_redis_commander
      HTTP_PASSWORD: sk_realtimeapp_redis_commander_password
    ports:
      - "8081:81"
    networks:
      - sk-realtimechat-network
    depends_on:
      - redis

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  rwt-net:
    driver: bridge
